spring:
  application:
    name: weather-gateway

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    city:
      path: /city/**
      serviceId: weather-city
    data:
      path: /data/**
      serviceId: weather-data