spring:
  application:
    name: weather-data
  redis:
    host: 192.168.33.100
    port: 6379

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/